### ISSUE TITLE
Unable to import from @devprotocol/dev-kit because of regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by taijusanagi** [dev-protocol/dev-kit-js#380]
## Expected Behavior
able to import { contractFactory } from "@devprotocol/dev-kit";

## Actual Behavior
following error happens

```
ReferenceError: regeneratorRuntime is not defined
    at /Users/taijusanagi/Documents/workspace/devprotocol-sandbox/node_modules/@devprotocol/dev-kit/dist/index.js:270:46
    at Object.<anonymous> (/Users/taijusanagi/Documents/workspace/devprotocol-sandbox/node_modules/@devprotocol/dev-kit/dist/index.js:312:2)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/taijusanagi/Documents/workspace/devprotocol-sandbox/test/integrate_with_dev_protocol.spec.ts:41:14)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module.m._compile (/Users/taijusanagi/Documents/workspace/devprotocol-sandbox/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/taijusanagi/Documents/workspace/devprotocol-sandbox/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
```

## Steps to Reproduce the Problem
1. create hardhat project
2. create test file which import as README suggested

```
import { contractFactory } from "@devprotocol/dev-kit";
```

3. run test

## Specifications

- Version: devprotocol/dev-kit@4.3.0
- Platform: macOS M1
- Subsystem: node v15, typescript

my project which faces above issue
https://github.com/taijusanagi/devprotocol-sandbox/tree/ba18b89dd93a9bdda22a745f3f7e27d367a736a7

**Comment by taijusanagi** [comment]
I was able to fix above issue by importing this before @devprotocol/dev-kit

```
import "regenerator-runtime/runtime.js";
```

This solution is suggested here.
https://github.com/babel/babel/issues/9849

I create this issue just want to report, and if there's another better way to fix this, please suggest me.

**Comment by aggre** [comment]
@taijusanagi Thanks for the report! I understand that the use of "regenerator-runtime/runtime" is a build environment-dependent issue.

However, it is possible to work around this issue by improving the bundling process with Rollup.

**Comment by aggre** [comment]
@taijusanagi This issue solved by the commit (https://github.com/dev-protocol/dev-kit-js/commit/43b8a07ff5e46de6421918f6c4e50aba48dee07c#diff-6814bf77564b4f1c92f5861e184e28fe217c080a047fefa8b73a728f755ec45c)
